Repository vaporvee/discord-sdk-godot, pull requests merged in 2023-05, with the labels that each got.

#21 fixed error when exporting project #20
  project/addons/discord-sdk-gd/export.gd
Labels: bug

#23 Adding overlay
  project/addons/discord-sdk-gd/bin/windows/discord_game_sdk_binding.dll
  project/addons/discord-sdk-gd/bin/windows/discord_game_sdk_binding_debug.dll
  project/main.gd
  project/project.godot
  src/discordgodot.cpp
  src/discordgodot.h
Labels: enhancement

#22 Added current user dictionary
  project/addons/discord-sdk-gd/bin/windows/discord_game_sdk_binding.dll
  project/addons/discord-sdk-gd/bin/windows/discord_game_sdk_binding_debug.dll
  project/main.gd
  project/main.tscn
  src/discordgodot.cpp
  src/discordgodot.h
Labels: enhancement

#27 Fix bugs and round up main for 2.0
  project/addons/discord-sdk-gd/bin/linux/libdiscord_game_sdk_binding.so
  project/addons/discord-sdk-gd/bin/linux/libdiscord_game_sdk_binding_debug.so
  project/addons/discord-sdk-gd/bin/windows/discord_game_sdk_binding.dll
  project/addons/discord-sdk-gd/bin/windows/discord_game_sdk_binding_debug.dll
  project/addons/discord-sdk-gd/export.gd
  project/addons/discord-sdk-gd/nodes/Debug.tscn
  project/addons/discord-sdk-gd/nodes/DiscordSDKLoader.tscn
  project/addons/discord-sdk-gd/nodes/assets/Checked.svg
  project/addons/discord-sdk-gd/nodes/assets/Checked.svg.import
  project/addons/discord-sdk-gd/nodes/assets/Debug.svg
  project/addons/discord-sdk-gd/nodes/assets/Debug.svg.import
  project/addons/discord-sdk-gd/nodes/assets/Group_1.svg
  project/addons/discord-sdk-gd/nodes/assets/Group_1.svg.import
  project/addons/discord-sdk-gd/nodes/assets/Unchecked.svg
  project/addons/discord-sdk-gd/nodes/assets/Unchecked.svg.import
  project/addons/discord-sdk-gd/nodes/assets/flow_spritesheet.png
  project/addons/discord-sdk-gd/nodes/assets/flow_spritesheet.png.import
  project/addons/discord-sdk-gd/nodes/core_updater.gd
  project/addons/discord-sdk-gd/nodes/debug.gd
  project/addons/discord-sdk-gd/plugin.cfg
  project/addons/discord-sdk-gd/plugin.gd
  project/addons/discord-sdk-gd/sdk_utility.gd
  project/assets/Checked.svg.import
  project/assets/Core Updater.png
  project/assets/Core Updater.svg
  project/assets/Debug.png
  project/assets/Debug.svg
  project/assets/Debug.svg.import
  project/discord_pfp_cache/invitepfp.png
  project/main.gd
  project/main.tscn
  project/project.godot
  src/discordgodot.cpp
  src/discordgodot.h
Labels: bug, enhancement

#29 Update export.gd to support extend environments
  project/addons/discord-sdk-gd/export.gd
Labels: bug
